### ISSUE TITLE
Add explicit include guards to each header file

### ISSUE THREAD

**Issue by tommymcm** [arcana-lab/noelle#105]
A lot of include files inside of NOELLE don't have include guards or rely on the flimsy `#pragma once`.

These should be modified to have the typical
```
#ifndef NOELLE_<NAME>_H_
#define NOELLE_<NAME>_H_
{ ... }
#endif // ifndef NOELLE_<NAME>_H_
```

I propose we use the `<PROJECT>_<PATH>_<FILENAME>_H_` format from Google's source code standard: https://google.github.io/styleguide/cppguide.html#The__define_Guard

For example:
`src/core/pdg/include/noelle/core/PDG.hpp` would use `NOELLE_CORE_PDG_PDG_H_` (note that src/ and include/ dirs would not be included).

**Comment by kala-ghoda** [comment]
Hi, I'd like to contribute to your project, and I think this would be a good first issue for me. Can I please take up this task?

**Comment by kala-ghoda** [comment]
Thanks for assigning the task, @tommymcm. I have pushed a PR in include-guard branch, waiting for your review.

**Comment by kala-ghoda** [comment]
@tommymcm thanks for the opportunity. Please let me know if there are any other issues that you think I could take up. Thanks!
