### ISSUE TITLE
Error when building NOELLE V14

### ISSUE THREAD

**Issue by randreshg** [arcana-lab/noelle#132]
`noelle/src/core/scheduler/src/Scheduler.cpp:859:64: error: expression list treated as compound expression in functional cast [-fpermissive]`

I think it is fixed by casting the set to a pointer of BasicBlock
``` 
this->Blocks = std::set<BasicBlock*>(
    this->TheLoop->getBasicBlocks().begin(), 
    this->TheLoop->getBasicBlocks().end()
);
```

**Comment by scampanoni** [comment]
It's interesting that it compiles for me. Which compiler are you using to compile NOELLE?
I'm using clang from LLVM 14.0.6

**Comment by scampanoni** [comment]
The latest commit includes the suggested change.
