### ISSUE TITLE
Error when NOELLE_SVF is ON

### ISSUE THREAD

**Issue by randreshg** [arcana-lab/noelle#135]
I get the following error when NOELLE_SVF=ON
`.build/_deps/noelle-src/src/core/pdg_generator/src/IntegrationWithSVF.cpp:31:12: fatal error: 'WPA/WPAPass.h' file not found`

**Comment by yiansu** [comment]
Hi Rafael, currently the NOELLE v14 branch does not have SVF support. We are currently working on the integration and you can expect an upgrade in a week.
