### ISSUE TITLE
LLVM 15 compatibility ?

### ISSUE THREAD

**Issue by ihiasi** [arcana-lab/noelle#61]
Any plans for a port to LLVM 15 or 16 ? Thank you.

**Comment by scampanoni** [comment]
Thank you for the question.
We will probably look into porting NOELLE to a later LLVM this coming year.
 
We didn't port NOELLE to the latest LLVM because LLVM improvements unlocked by the latest LLVM don't impact our research; so porting became less important (but we'll do it next year).
